"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var PalworldBlacklistSettingsEnum;
(function (PalworldBlacklistSettingsEnum) {
    PalworldBlacklistSettingsEnum["ActiveUNKO"] = "ActiveUNKO";
    PalworldBlacklistSettingsEnum["EnableAimAssistPad"] = "EnableAimAssistPad";
    PalworldBlacklistSettingsEnum["EnableAimAssistKeyboard"] = "EnableAimAssistKeyboard";
    PalworldBlacklistSettingsEnum["DropItemMaxNum_UNKO"] = "DropItemMaxNum_UNKO";
    PalworldBlacklistSettingsEnum["AutoResetGuildNoOnlinePlayers"] = "AutoResetGuildNoOnlinePlayers";
    PalworldBlacklistSettingsEnum["AutoResetGuildTimeNoOnlinePlayers"] = "AutoResetGuildTimeNoOnlinePlayers";
    PalworldBlacklistSettingsEnum["GuildPlayerMaxNum"] = "GuildPlayerMaxNum";
    PalworldBlacklistSettingsEnum["IsMultiplay"] = "IsMultiplay";
    PalworldBlacklistSettingsEnum["IsPvP"] = "IsPvP";
    PalworldBlacklistSettingsEnum["EnableNonLoginPenalty"] = "EnableNonLoginPenalty";
    PalworldBlacklistSettingsEnum["ExistPlayerAfterLogout"] = "ExistPlayerAfterLogout";
    PalworldBlacklistSettingsEnum["EnableDefenseOtherGuildPlayer"] = "EnableDefenseOtherGuildPlayer";
    PalworldBlacklistSettingsEnum["CoopPlayerMaxNum"] = "CoopPlayerMaxNum";
    PalworldBlacklistSettingsEnum["ServerPlayerMaxNum"] = "ServerPlayerMaxNum";
    PalworldBlacklistSettingsEnum["ServerName"] = "ServerName";
    PalworldBlacklistSettingsEnum["ServerDescription"] = "ServerDescription";
    PalworldBlacklistSettingsEnum["AdminPassword"] = "AdminPassword";
    PalworldBlacklistSettingsEnum["ServerPassword"] = "ServerPassword";
    PalworldBlacklistSettingsEnum["PublicPort"] = "PublicPort";
    PalworldBlacklistSettingsEnum["PublicIP"] = "PublicIP";
    PalworldBlacklistSettingsEnum["RCONEnabled"] = "RCONEnabled";
    PalworldBlacklistSettingsEnum["RCONPort"] = "RCONPort";
    PalworldBlacklistSettingsEnum["Region"] = "Region";
    PalworldBlacklistSettingsEnum["UseAuth"] = "UseAuth";
    PalworldBlacklistSettingsEnum["BanListURL"] = "BanListURL";
    PalworldBlacklistSettingsEnum["RESTAPIEnabled"] = "RESTAPIEnabled";
    PalworldBlacklistSettingsEnum["RESTAPIPort"] = "RESTAPIPort";
    PalworldBlacklistSettingsEnum["ShowPlayerList"] = "ShowPlayerList";
    PalworldBlacklistSettingsEnum["AllowConnectPlatform"] = "AllowConnectPlatform";
    PalworldBlacklistSettingsEnum["IsUseBackupSaveData"] = "IsUseBackupSaveData";
    PalworldBlacklistSettingsEnum["LogFormatType"] = "LogFormatType";
    PalworldBlacklistSettingsEnum["EnablePlayerToPlayerDamage"] = "EnablePlayerToPlayerDamage";
    PalworldBlacklistSettingsEnum["EnableFriendlyFire"] = "EnableFriendlyFire";
    PalworldBlacklistSettingsEnum["EnableInvaderEnemy"] = "EnableInvaderEnemy";
    PalworldBlacklistSettingsEnum["CanPickupOtherGuildDeathPenaltyDrop"] = "CanPickupOtherGuildDeathPenaltyDrop";
    PalworldBlacklistSettingsEnum["IsStartLocationSelectByMap"] = "IsStartLocationSelectByMap";
    PalworldBlacklistSettingsEnum["EnableFastTravel"] = "EnableFastTravel";
    PalworldBlacklistSettingsEnum["None"] = "None";
})(PalworldBlacklistSettingsEnum || (PalworldBlacklistSettingsEnum = {}));
exports.default = PalworldBlacklistSettingsEnum;
