
enum PalworldBlacklistSettingsEnum
{
    ActiveUNKO = "ActiveUNKO",
    EnableAimAssistPad = "EnableAimAssistPad",
    EnableAimAssistKeyboard = "EnableAimAssistKeyboard",
    DropItemMaxNum_UNKO = "DropItemMaxNum_UNKO",
    AutoResetGuildNoOnlinePlayers = "AutoResetGuildNoOnlinePlayers",
    AutoResetGuildTimeNoOnlinePlayers = "AutoResetGuildTimeNoOnlinePlayers",
    GuildPlayerMaxNum = "GuildPlayerMaxNum",
    IsMultiplay = "IsMultiplay",
    IsPvP = "IsPvP",
    EnableNonLoginPenalty = "EnableNonLoginPenalty",
    ExistPlayerAfterLogout = "ExistPlayerAfterLogout",
    EnableDefenseOtherGuildPlayer = "EnableDefenseOtherGuildPlayer",
    CoopPlayerMaxNum = "CoopPlayerMaxNum",
    ServerPlayerMaxNum = "ServerPlayerMaxNum",
    ServerName = "ServerName",
    ServerDescription = "ServerDescription",
    AdminPassword = "AdminPassword",
    ServerPassword = "ServerPassword",
    PublicPort = "PublicPort",
    PublicIP = "PublicIP",
    RCONEnabled = "RCONEnabled",
    RCONPort = "RCONPort",
    Region = "Region",
    UseAuth = "UseAuth",
    BanListURL = "BanListURL",
    RESTAPIEnabled = "RESTAPIEnabled",
    RESTAPIPort = "RESTAPIPort",
    ShowPlayerList = "ShowPlayerList",
    AllowConnectPlatform = "AllowConnectPlatform",
    IsUseBackupSaveData = "IsUseBackupSaveData",
    LogFormatType = "LogFormatType",
    EnablePlayerToPlayerDamage = "EnablePlayerToPlayerDamage",
    EnableFriendlyFire = "EnableFriendlyFire",
    EnableInvaderEnemy = "EnableInvaderEnemy",
    CanPickupOtherGuildDeathPenaltyDrop = "CanPickupOtherGuildDeathPenaltyDrop",
    IsStartLocationSelectByMap = "IsStartLocationSelectByMap",
    EnableFastTravel = "EnableFastTravel",
    None = "None"
}

export default PalworldBlacklistSettingsEnum;